### ISSUE TITLE
Use ssh.putMulti instead of ssh.put

### ISSUE THREAD

**Issue by steelbrain** [AutoCloud/ember-cli-deploy-simply-ssh#1]
`ssh.put` requests a different `sftp` for each file, whereas `putMulti` reuses the same for all the files

**Comment by youroff** [comment]
It was there:
https://github.com/AutoCloud/ember-cli-deploy-simply-ssh/blob/262c324200fde72f63cfafcfd1724efddadac5ef/lib/ssh.js#L46-L54
But I didn't seem to reuse the same sftp-session, so I tried to reimplement that and eventually found that setting for sshd. Will look closer, anyways.

**Comment by youroff** [comment]
Isn't this effectively the same? https://github.com/steelbrain/node-ssh/blob/master/Source/SSH.js#L153-L155

**Comment by steelbrain** [comment]
[The current implementation](https://github.com/AutoCloud/ember-cli-deploy-simply-ssh/blob/3ea90ba9afaa4d78cb32d5710b2ecfaebd3c7d83/lib/ssh.js#L55-L57) is only passing two args to `ssh.put` so to fill the third one, it requests a SFTP object each time. You can requestSFTP and then pass it as a third arg and it'll use that

**Comment by youroff** [comment]
Oh, I haven't read sources when making this plugin, so I got an impression that as long as it's called from node_ssh instance, then connection is established and is going to be used implicitly. But if we use single connection instance, is there some run-loop that makes files delivered sequentially? Cause I can swear I had the same issue with MaxSessions while using putMulti.

**Comment by steelbrain** [comment]
If you want to write files sequentially, here's how can you do that
```
files.reduce(function(promise, file) {
  return promise.then(function(){
    return ssh.put(file, remotePath(file))
  })
}, Promise.resolve()
```

**Comment by youroff** [comment]
Oh, looks neat, I'll try that, thank you :)
