### ISSUE TITLE
Not uploading index.html

### ISSUE THREAD

**Issue by gilles-bertrand** [AutoCloud/ember-cli-deploy-simply-ssh#2]
Hello, 
I'm using the addon but it doesn't upload my index.html file.
Is this normal ?

**Comment by youroff** [comment]
Nope. Could you post versions of other plugins from ember-cli-deploy stack?

**Comment by youroff** [comment]
@TheCrazyDigitalPainter should I close this issue or the problem still exists with up-to-date deploy stack?

**Comment by corepoint-cio** [comment]
I am experiencing this problem. I note that you had asked for the version of the ember-cli-deploy stack. Here are mine (I only just installed everything):
"ember-cli-deploy": "^1.0.2",
    "ember-cli-deploy-build": "^1.1.1",
    "ember-cli-deploy-gzip": "^1.0.1",
    "ember-cli-deploy-revision-data": "^1.0.0",
    "ember-cli-deploy-simply-ssh": "^1.0.0",
All the other files are there and the current link is working fine, but no index.html file is uploaded or present. The Uploaded file list does not include it either.
Is this a bug, or am I doing something wrong?
I was executing `ember deploy staging --activate`
Even without the --activate there was no index.html file. And yes, its is present in my /dist folder.

**Comment by erzzo** [comment]
Hi,
I'm experiencing the same issue.

``` json
"ember-cli-deploy": "^1.0.2",
"ember-cli-deploy-build": "^1.1.1",
"ember-cli-deploy-compress": "^0.2.0",
"ember-cli-deploy-simply-ssh": "^1.0.0"
```

**Comment by erzzo** [comment]
It's looks like this was the issue https://github.com/AutoCloud/ember-cli-deploy-simply-ssh/commit/511a0b1d3c78cea7332f36f62617d93e5a9a4328

please publish a new version :+1:

**Comment by youroff** [comment]
Done ;)
