### ISSUE TITLE
Usage with ember-cli-deploy-gzip might be confusing

### ISSUE THREAD

**Issue by mydea** [AutoCloud/ember-cli-deploy-simply-ssh#3]
Just writing it here, as it bit me: When trying to use this with ember-cli-deploy-gzip, it will not include any .html and image files (.png, .gif, .jpg), as those are by default not processed by ember-cli-deploy-gzip.

This led to all the images not being uploaded for me (as well as the index.html). I removed ember-cli-deploy-gzip - maybe it would make sense to note this in the readme?

**Comment by youroff** [comment]
Oh, thank you for heads up. Probably the behavior of `-gzip` changed. I'll provide a fix soon, so it would merge gzipped content with regular content.

**Comment by mydea** [comment]
Great!

By the way, I'm using this on a Windows machine, and it is working perfectly when used in Git Bash.

**Comment by youroff** [comment]
I assume it's posix? If yes, it's not really relevant, cause I was wondering about path generation under Windows.

**Comment by mydea** [comment]
In the regular cmd, I get this error:

```
Error: Unexpected disconnection from agent
Error: Unexpected disconnection from agent
    at PageantSock.onclose (C:\...\node_modules\ssh2\lib\agent.js:179:10)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at PageantSock.emit (events.js:210:7)
    at ChildProcess.<anonymous> (C:\...\node_modules\ssh2\lib\agent.js:398:12)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
Pipeline aborted
```

(with agent='pageant' - the same config that works in Git Bash).

**Comment by youroff** [comment]
Yeah, need to install windows and try. If you can figure out what's wrong with ssh2 when called under cmd, PR will be appreciated. I guess some tweaks to connection params needed.
