### ISSUE TITLE
Deploy fails when revisions.json is missing

### ISSUE THREAD

**Issue by bummzack** [AutoCloud/ember-cli-deploy-simply-ssh#6]
When starting a new deployment into an empty directory, the plugin will fail in the `didUpload` hook with an error like:

 > cat: /www/releases/revisions.json: No such file or directory

Creating an empty file at `/www/releases/revisions.json` solves the issue (there's a json-syntax error, which is to be expected, but the deploy completes).

I think a fix would involve checking if the `revisions.json` file exists prior to reading it… so that first-time deployments complete properly.

**Comment by youroff** [comment]
Thanks for heads up, I'll look into it. If you can provide a PR, it would be highly appreciated. I think a quick fix here would be something like:
```
const cmd = "([ -e " + revPath + " ] || echo \"[]\" >> " + revPath + ") && cat " + revPath
```
https://github.com/AutoCloud/ember-cli-deploy-simply-ssh/blob/master/index.js#L129
